# Configuration for PR auto-labeling

documentation:
  - changed-files:
    - any-glob-to-any-file:
      - "**/*.md"
      - "docs/**"

firmware:
  - changed-files:
    - any-glob-to-any-file:
      - "keyboards/**"
      - "quantum/**"
      - "tmk_core/**"
      - "drivers/**"

build:
  - changed-files:
    - any-glob-to-any-file:
      - "builddefs/**"
      - "build.py"
      - "Makefile"
      - "**/*.mk"

ci/cd:
  - changed-files:
    - any-glob-to-any-file:
      - ".github/workflows/**"
      - ".github/actions/**"

dependencies:
  - changed-files:
    - any-glob-to-any-file:
      - "requirements*.txt"
      - "lib/**"
      - ".gitmodules"

pointing-device:
  - changed-files:
    - any-glob-to-any-file:
      - "**/pointing_device*"
      - "**/trackball*"
      - "**/tps43*"
      - "**/trackpoint*"

vial:
  - changed-files:
    - any-glob-to-any-file:
      - "**/vial*"
      - "**/via*"
