VIA_ENABLE = yes
VIAL_ENABLE = yes
OLED_ENABLE = yes
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = yes
TAP_DANCE_ENABLE = no
COMBO_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
BOOTMAGIC_ENABLE = lite
LTO_ENABLE = yes

# Use shared holykeebs OLED implementation to save flash on AVR splits.
HK_OLED_ENABLE = yes
OPT_DEFS += -DHK_OLED_ENABLE
